/*
 * TODO:
 * * A20 line
 * * NMIs
 */

#include <stdbool.h>

typedef unsigned char   uint8_t;
typedef unsigned short  uint16_t;
typedef unsigned int    uint32_t;

static void _putc(char c)
{
    __asm__ volatile("out %%al, %%dx" ::"a"(c), "d"(0x402):);
}

static void _puts(const char* s)
{
    while (*s != '\0') {
        _putc(*s++);
    }
}

static void _putline(void)
{
    _putc('\n');
}

static char _hex2char(uint8_t v)
{
    return (v <= 9 ? '0' + v : 'A' - 0xA + v);
}

static void _putx8(uint8_t v)
{
    _putc(_hex2char((v & 0xF0) >> 4));
    _putc(_hex2char(v & 0x0F));
}

static void _putx16(uint16_t v)
{
    __asm__ volatile("xchg %%al, %%ah" :"=a"(v) :"a"(v) :);
    
    _puts("0x");
    for (unsigned i = 0; i < 2; ++i) {
        _putx8(v & 0xFF);
        v >>= 8;
    }
}

static void _putx32(uint32_t v)
{
    __asm__ volatile("bswap %%eax" :"=a"(v) :"a"(v) :);
    
    _puts("0x");
    for (unsigned i = 0; i < 4; ++i) {
        _putx8(v & 0xFF);
        v >>= 8;
    }
}

/**
 * Exception frame record.
 * Generated by assembly code, order of fields is important.
 */
struct exception_frame32 {
    uint32_t edi;
    uint32_t esi;
    uint32_t ebp;
    uint32_t esp;
    uint32_t ebx;
    uint32_t edx;
    uint32_t ecx;
    uint32_t eax;
    uint32_t error_code;
    uint32_t eip;
    uint16_t cs;
    uint16_t _pad;
    uint32_t eflags;
};

void exception_handler(unsigned long num, struct exception_frame32* frame)
{
    _puts("Exception "); _putx16(num); _putline();
    _puts("CS: "); _putx16(frame->cs); _putline();
    _puts("EIP: "); _putx32(frame->eip); _putline();
    _puts("EFLAGS: "); _putx32(frame->eflags); _putline();
    _puts("Error code: "); _putx32(frame->error_code); _putline();
    _puts("EAX: "); _putx32(frame->eax); _putline();
    _puts("EBX: "); _putx32(frame->ebx); _putline();
    _puts("ECX: "); _putx32(frame->ecx); _putline();
    _puts("EDX: "); _putx32(frame->edx); _putline();
    _puts("EDI: "); _putx32(frame->edi); _putline();
    _puts("ESI: "); _putx32(frame->esi); _putline();
    _puts("EBP: "); _putx32(frame->ebp); _putline();
    _puts("ESP: "); _putx32(frame->esp); _putline();
}

int main(void)
{
    _puts("Hello world\n");
    _putx32(0xDEADF00D);
    _putline();

    return 0;
}

int _start(void)
{
    return main();
}
